/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.util.List;
import beans.*;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jms.Destination;
import javax.jms.JMSConsumer;
import javax.jms.JMSContext;
import javax.jms.JMSException;
import javax.jms.JMSProducer;
import javax.jms.Message;
import javax.jms.ObjectMessage;
import javax.swing.JButton;
import javax.swing.JPanel;
import messages.Login;
import messages.SobeMessage;
import utils.Helpers;
import utils.TipZahteva;

/**
 *
 * @author malenicn
 */
public class HomePanel extends javax.swing.JFrame {

    public void refresh() {
        if (!this.isVisible()) {
            this.setVisible(true);
        }
        HomePanel np = new HomePanel();
        Point point = this.getLocationOnScreen();
        np.setLocation((int) point.getX(), (int) point.getY());
        np.setVisible(true);
        this.dispose();
    }

    private List<Soba> sobe;

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();

        dohvatiSobe();

        this.setLayout(new GridLayout(sobe.size(), 1));
        for (int i = 0; i < sobe.size(); i++) {
            JButton glavno = new JButton(sobe.get(i).getApartman().getIme() + "(" + sobe.get(i).getRedBr() + ")");

            // paneli za resizing
            JPanel gp = new JPanel();
            gp.add(glavno);

            glavno.setPreferredSize(new Dimension(200, 40));

            glavno.addActionListener(new ActionListener() {
                private Soba s;
                private HomePanel panel;

                public void actionPerformed(ActionEvent e) {
                    new Rezervacije(s, "").setVisible(true);
                    panel.setVisible(false);
                }

                private ActionListener init(Soba s, HomePanel panel) {
                    this.s = s;
                    this.panel = panel;
                    return this;
                }
            }.init(sobe.get(i), this));

            this.add(gp);
        }
        JMSContext context = kupac.Kupac.connectionFactory.createContext();
        JMSConsumer consumer = context.createConsumer(kupac.Kupac.obavestenjaSobe);
        consumer.setMessageListener(new SobeListener(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closingHandler(evt);
            }
        });

        jMenu2.setText("Akcije");

        jMenuItem1.setText("Promena korisnickih podataka");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new PromenaKorisnickihPodataka().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void closingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closingHandler
        this.dispose();
    }//GEN-LAST:event_closingHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    public void dohvatiSobe() {
        JMSContext context = kupac.Kupac.connectionFactory.createContext();

        Destination destination = kupac.Kupac.zahtevi;
        String username = kupac.Kupac.kupac.getUsername();
        String password = kupac.Kupac.kupac.getPassword();

        JMSConsumer consumer = context.createConsumer(kupac.Kupac.odgovori, Helpers.getId(username, password));
        JMSProducer producer = context.createProducer();

        Login login = new Login(username, password);
        ObjectMessage zahtev = context.createObjectMessage();
        try {
            zahtev.setStringProperty("id", username + password);

            zahtev.setObject("");
            zahtev.setIntProperty("tip", TipZahteva.DOHVATANJE_SVIH_SOBA.ordinal());

            producer.send(destination, zahtev);
        } catch (JMSException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        Message odgovor = consumer.receive();
        if (odgovor instanceof ObjectMessage) {
            try {
                Object objekat = ((ObjectMessage) odgovor).getObject();
                if (objekat != null) {

                    this.sobe = ((SobeMessage) objekat).getSobe();
                } else {
                    // this.sobe = new ArrayList<>();
                }
            } catch (JMSException ex) {
                Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }

    }
}
